/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#d3daea',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'on-surface': '#151c27',
        'on-surface-variant': '#3c4a42',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        outline: '#6c7a71',
        'outline-variant': '#bbcabf',
        'surface-tint': '#006c49',
        primary: '#006c49',
        'on-primary': '#ffffff',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'inverse-primary': '#4edea3',
        secondary: '#2b6954',
        'on-secondary': '#ffffff',
        'secondary-container': '#adedd3',
        'on-secondary-container': '#306d58',
        tertiary: '#005ac2',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#71a1ff',
        'on-tertiary-container': '#00367a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        background: '#f9f9ff',
        'on-background': '#151c27',
        'surface-variant': '#dce2f3',
        'tertiary-fixed': '#d8e2ff',
        'on-tertiary-fixed': '#001a42',
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
        },
      },
      fontFamily: {
        sans: ['Inter_400Regular'],
        'sans-medium': ['Inter_500Medium'],
        'sans-semibold': ['Inter_600SemiBold'],
        'sans-bold': ['Inter_700Bold'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em' }],
        'headline-sm': ['20px', { lineHeight: '28px' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'label-md': ['12px', { lineHeight: '16px' }],
        'numeric-data': ['18px', { lineHeight: '24px' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'stack-gap': '12px',
        'container-margin': '16px',
      },
      borderRadius: {
        xl: '12px',
        '2xl': '16px',
      },
    },
  },
  plugins: [],
};
