/** @type {import('tailwindcss').Config} */
const { colors, spacing, radius, fontSize, duration } = require('./constants/theme.ts');

module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        brand: {
          ...colors.brand,
          600: colors.brand.dark,
          700: colors.brand.deeper,
        },
        red: colors.red,
        blue: colors.blue,
        amber: colors.amber,
        gray: colors.gray,
        // Semantic aliases — maps existing class names to the new palette
        surface: colors.gray[50],
        'surface-dim': colors.gray[50],
        'surface-bright': colors.gray[50],
        'surface-container-lowest': '#ffffff',
        'surface-container-low': colors.brand.light,
        'surface-container': colors.brand.light,
        'surface-container-high': colors.brand.light,
        'surface-container-highest': colors.gray[50],
        'on-surface': colors.gray[900],
        'on-surface-variant': colors.gray[400],
        'inverse-surface': colors.gray[900],
        'inverse-on-surface': colors.gray[50],
        outline: colors.gray[400],
        'outline-variant': colors.gray[50],
        'surface-tint': colors.brand.dark,
        primary: colors.brand.dark,
        'on-primary': '#ffffff',
        'primary-container': colors.brand.light,
        'on-primary-container': colors.brand.deeper,
        'inverse-primary': colors.brand.dark,
        secondary: colors.brand.deeper,
        'on-secondary': '#ffffff',
        'secondary-container': colors.brand.light,
        'on-secondary-container': colors.brand.deeper,
        tertiary: colors.blue.default,
        'on-tertiary': '#ffffff',
        'tertiary-container': colors.blue.light,
        'on-tertiary-container': colors.blue.default,
        error: colors.red.default,
        'on-error': '#ffffff',
        'error-container': colors.red.light,
        'on-error-container': colors.red.default,
        'primary-fixed': colors.brand.light,
        'primary-fixed-dim': colors.brand.primary,
        background: colors.gray[50],
        'on-background': colors.gray[900],
        'surface-variant': colors.gray[50],
        'tertiary-fixed': colors.blue.light,
        'on-tertiary-fixed': colors.blue.default,
      },
      fontFamily: {
        sans: ['Inter_400Regular', 'Inter', 'sans-serif', { fontWeight: '400' }],
        'sans-medium': ['Inter_500Medium', 'Inter', 'sans-serif', { fontWeight: '500' }],
        'sans-semibold': ['Inter_600SemiBold', 'Inter', 'sans-serif', { fontWeight: '600' }],
        'sans-bold': ['Inter_700Bold', 'Inter', 'sans-serif', { fontWeight: '700' }],
      },
      fontSize: {
        display: [`${fontSize.display}px`, { lineHeight: `${fontSize.display + 8}px` }],
        h1: [`${fontSize.h1}px`, { lineHeight: `${fontSize.h1 + 8}px` }],
        h2: [`${fontSize.h2}px`, { lineHeight: `${fontSize.h2 + 6}px` }],
        h3: [`${fontSize.h3}px`, { lineHeight: `${fontSize.h3 + 6}px` }],
        body: [`${fontSize.body}px`, { lineHeight: `${fontSize.body + 6}px` }],
        small: [`${fontSize.small}px`, { lineHeight: `${fontSize.small + 5}px` }],
        caption: [`${fontSize.caption}px`, { lineHeight: `${fontSize.caption + 4}px` }],
        // Legacy aliases used across components
        'display-lg': [`${fontSize.display + 4}px`, { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'display-lg-mobile': [`${fontSize.display}px`, { lineHeight: '36px', letterSpacing: '-0.02em' }],
        'headline-md': [`${fontSize.h1 + 2}px`, { lineHeight: '32px', letterSpacing: '-0.01em' }],
        'headline-sm': [`${fontSize.h2 + 2}px`, { lineHeight: '28px' }],
        'body-lg': [`${fontSize.h3}px`, { lineHeight: '24px' }],
        'body-md': [`${fontSize.body}px`, { lineHeight: '20px' }],
        'label-md': [`${fontSize.caption}px`, { lineHeight: '16px' }],
        'numeric-data': [`${fontSize.h2}px`, { lineHeight: '24px' }],
      },
      spacing: {
        xs: `${spacing.xs}px`,
        sm: `${spacing.sm}px`,
        md: `${spacing.md}px`,
        lg: `${spacing.lg}px`,
        xl: `${spacing.xl}px`,
        '2xl': `${spacing['2xl']}px`,
        '3xl': `${spacing['3xl']}px`,
        'stack-gap': `${spacing.md}px`,
        'container-margin': `${spacing.lg}px`,
      },
      borderRadius: {
        sm: `${radius.sm}px`,
        md: `${radius.md}px`,
        lg: `${radius.lg}px`,
        pill: `${radius.pill}px`,
        full: `${radius.full}px`,
        xl: `${radius.lg}px`,
        '2xl': '16px',
      },
      transitionDuration: {
        fast: `${duration.fast}ms`,
        standard: `${duration.standard}ms`,
        complex: `${duration.complex}ms`,
      },
    },
  },
  plugins: [],
};
