/** @type {import('tailwindcss').Config} */
const { colors, spacing, radius, fontSize, duration } = require('./constants/theme.ts');

module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        brand: {
          ...colors.brand,
          600: colors.brand.dark,
          700: colors.brand.deeper,
        },
        red: colors.red,
        blue: colors.blue,
        amber: colors.amber,
        gray: colors.gray,
        // Semantic aliases — CSS variables switch in light/dark via global.css
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--background) / <alpha-value>)',
        outline: 'rgb(var(--outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        'surface-tint': colors.brand.dark,
        primary: colors.brand.dark,
        'on-primary': '#ffffff',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'inverse-primary': colors.brand.dark,
        secondary: colors.brand.deeper,
        'on-secondary': '#ffffff',
        'secondary-container': 'rgb(var(--secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container) / <alpha-value>)',
        tertiary: colors.blue.default,
        'on-tertiary': '#ffffff',
        'tertiary-container': colors.blue.light,
        'on-tertiary-container': colors.blue.default,
        error: colors.red.default,
        'on-error': '#ffffff',
        'error-container': 'rgb(var(--error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--on-error-container) / <alpha-value>)',
        'primary-fixed': colors.brand.light,
        'primary-fixed-dim': colors.brand.primary,
        background: 'rgb(var(--background) / <alpha-value>)',
        'on-background': 'rgb(var(--on-surface) / <alpha-value>)',
        'surface-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        'tertiary-fixed': colors.blue.light,
        'on-tertiary-fixed': colors.blue.default,
      },
      fontFamily: {
        sans: ['Inter_400Regular', 'Inter', 'sans-serif', { fontWeight: '400' }],
        'sans-medium': ['Inter_500Medium', 'Inter', 'sans-serif', { fontWeight: '500' }],
        'sans-semibold': ['Inter_600SemiBold', 'Inter', 'sans-serif', { fontWeight: '600' }],
        'sans-bold': ['Inter_700Bold', 'Inter', 'sans-serif', { fontWeight: '700' }],
      },
      fontSize: {
        display: [`${fontSize.display}px`, { lineHeight: `${fontSize.display + 8}px` }],
        h1: [`${fontSize.h1}px`, { lineHeight: `${fontSize.h1 + 8}px` }],
        h2: [`${fontSize.h2}px`, { lineHeight: `${fontSize.h2 + 8}px` }],
        h3: [`${fontSize.h3}px`, { lineHeight: `${fontSize.h3 + 8}px` }],
        body: [`${fontSize.body}px`, { lineHeight: `${fontSize.body + 8}px` }],
        small: [`${fontSize.small}px`, { lineHeight: `${fontSize.small + 9}px` }],
        caption: [`${fontSize.caption}px`, { lineHeight: `${fontSize.caption + 8}px` }],
        // Legacy aliases used across components
        'display-lg': [`${fontSize.display + 4}px`, { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'display-lg-mobile': [`${fontSize.display}px`, { lineHeight: '36px', letterSpacing: '-0.02em' }],
        'headline-md': [`${fontSize.h1 + 2}px`, { lineHeight: '32px', letterSpacing: '-0.01em' }],
        'headline-sm': [`${fontSize.h2 + 2}px`, { lineHeight: '28px' }],
        'body-lg': [`${fontSize.h3}px`, { lineHeight: '24px' }],
        'body-md': [`${fontSize.body}px`, { lineHeight: '22px' }],
        'label-md': [`${fontSize.caption}px`, { lineHeight: '20px' }],
        'numeric-data': [`${fontSize.h2}px`, { lineHeight: '26px' }],
      },
      spacing: {
        xs: `${spacing.xs}px`,
        sm: `${spacing.sm}px`,
        md: `${spacing.md}px`,
        lg: `${spacing.lg}px`,
        xl: `${spacing.xl}px`,
        '2xl': `${spacing['2xl']}px`,
        '3xl': `${spacing['3xl']}px`,
        'stack-gap': `${spacing.md}px`,
        'section-gap': `${spacing.lg}px`,
        'container-margin': `${spacing.lg}px`,
      },
      borderRadius: {
        sm: `${radius.sm}px`,
        md: `${radius.md}px`,
        lg: `${radius.lg}px`,
        pill: `${radius.pill}px`,
        full: `${radius.full}px`,
        xl: `${radius.lg}px`,
        '2xl': '16px',
      },
      transitionDuration: {
        fast: `${duration.fast}ms`,
        standard: `${duration.standard}ms`,
        complex: `${duration.complex}ms`,
      },
    },
  },
  plugins: [],
};
